/*
 * Communication.h
 *
 *  Created on: Aug 29, 2015
 *      Author: TRAN THANH XUAN
 */

#ifndef GOOGLECAR_15_9_IMPPROCESS_FAIL_COMMUNICATION_COMMUNICATION_H_
#define GOOGLECAR_15_9_IMPPROCESS_FAIL_COMMUNICATION_COMMUNICATION_H_
extern void GetData(void);
#endif /* GOOGLECAR_15_9_IMPPROCESS_FAIL_COMMUNICATION_COMMUNICATION_H_ */
